// Project info

name := "play-mongo-jackson-mapper"

organization := "net.vz.mongodb.jackson"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.10.0"

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Dependencies

libraryDependencies ++= Seq(
    "net.vz.mongodb.jackson" % "mongo-jackson-mapper" % "1.4.1",
    "com.fasterxml" % "jackson-module-scala" % "1.9.3",
    "play" %% "play" % "2.1-RC2"
)

// Test dependencies

libraryDependencies ++= Seq(
    "org.specs2" %% "specs2" % "1.13" % "test",
    "play" %% "play-test" % "2.1-RC2" % "test"
)

// Configuration required for deploying to sonatype

publishMavenStyle := true

publishTo := Some(Resolver.sftp("Patience", "repo.patience.io", "repo"))

pomIncludeRepository := { _ => false }

publishArtifact in Test := false

pomExtra := (
  <url>http://github.com/vznet/play-mongo-jackson-mapper</url>
  <inceptionYear>2012</inceptionYear>
  <licenses>
    <license>
      <name>Apache 2</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
      <comments>A business-friendly OSS license</comments>
    </license>
  </licenses>
  <scm>
    <url>git@github.com:vznet/play-mongo-jackson-mapper.git</url>
    <connection>scm:git:git@github.com:vznet/play-mongo-jackson-mapper.git</connection>
  </scm>
  <developers>
    <developer>
      <name>James Roper</name>
      <email>james@jazzy.id.au</email>
      <url>http://jazzy.id.au</url>
      <roles>
        <role>Author</role>
      </roles>
      <organization>VZ Netzwerke</organization>
    </developer>
  </developers>)
